version: '2'
services:
  postgresql:
    image: postgres:10-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password

  vault:
    image: vault:0.9.3
    ports:
      - "8200:8200"
    environment:
      - SKIP_SETCAP=1
      - VAULT_DEV_ROOT_TOKEN_ID=devToken

  localstack:
    image: localstack/localstack:0.10.5
    environment:
      - SERVICES=iam:4593,sqs:4576,sns:4575,s3:4572,sts:4592
      - DEFAULT_REGION=eu-west-1
      - DEBUG=1
      - TEST_AWS_ACCOUNT_ID=123456789012

  wait_for:
    image: dadarek/wait-for-dependencies
    depends_on:
      - postgresql
      - vault
    command: postgresql:5432 vault:8200

  indoor_terraform:
    image: ${PRIMARY_DOCKER_REGISTRY}/tech.form3/form3-terraform-bundle:0.12-develop
    volumes:
      - ./tf:/tf
      - ./tf_test_overrides:/tf_test_overrides
    depends_on:
      - postgresql
      - vault
      - wait_for
    environment:
      TFE_TOKEN: ${TFE_TOKEN}
      TF_VAR_environment: local
      TF_VAR_api_vault_address: http://vault:8200
      TF_VAR_api_vault_token: 'devToken'
      TF_VAR_stack_name: local
      TF_VAR_psql_user: postgres
      TF_VAR_psql_password: password
      TF_VAR_psql_host: postgresql
      TF_VAR_psql_port: 5432
